name: polyaxon-X-Train
channels:
  - defaults
dependencies:
  - python=3.6.7
  - pip=19.0.3
  - cudnn=7.6.4 # for running gpu on polyaxon
  - numpy=1.19.2 # so we get the mkl libs as well
  - pip:
    - openpyxl==3.0.7
    - polyaxon-client==0.5.6
    - argparse==1.1
    - pandas==1.1.3
    - tensorflow==2.3.0
    - transformers==4.2.2
    - demjson==2.2.4
